name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history for version bump commit

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Use the Node.js version your package requires
          registry-url: "https://registry.npmjs.org"

      # Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install

      # Fetch latest version and bump in package.json
      - name: Set latest version from npm
        run: |
          # Fetch the latest version from npm
          LATEST_VERSION=$(npm info . version)
          jq --arg version "$LATEST_VERSION" '.version = $version' package.json > package.tmp && mv package.tmp package.json
          npm version patch --no-git-tag-version

      # Publish to npm
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
